"""Generate engine/src/unicode_data.h: code point ranges for the tokenizer.

    python engine/tools/gen_unicode.py > engine/src/unicode_data.h

The GPT-2 split pattern that byte-level BPE tokenizers use names three
classes: \\p{L} (letters: Lu, Ll, Lt, Lm, Lo), \\p{N} (numbers: Nd, Nl, No) and
\\s. The first two come from this Python's unicodedata, whose Unicode version
is written into the header. \\s is the White_Space property, a short fixed
list kept in unicode.c.
"""

import sys
import unicodedata


def ranges(pred):
    out = []
    start = None
    for cp in range(0x110000):
        hit = pred(cp)
        if hit and start is None:
            start = cp
        elif not hit and start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, 0x10FFFF))
    return out


def category_in(prefixes):
    return lambda cp: unicodedata.category(chr(cp)) in prefixes


def emit(name, rs):
    print(f"static const uint32_t {name}[][2] = {{")
    line = "   "
    for a, b in rs:
        item = f" {{0x{a:X}, 0x{b:X}}},"
        if len(line) + len(item) > 100:
            print(line)
            line = "   "
        line += item
    print(line)
    print("};")
    print(f"#define {name}_COUNT {len(rs)}")
    print()


def main():
    letters = ranges(category_in({"Lu", "Ll", "Lt", "Lm", "Lo"}))
    numbers = ranges(category_in({"Nd", "Nl", "No"}))
    print("/* Generated by engine/tools/gen_unicode.py. Do not edit. */")
    print(f"/* Unicode {unicodedata.unidata_version}, from Python {sys.version.split()[0]}'s unicodedata. */")
    print()
    print("#ifndef VITNA_UNICODE_DATA_H")
    print("#define VITNA_UNICODE_DATA_H")
    print()
    print("#include <stdint.h>")
    print()
    print(f'#define VITNA_UNICODE_VERSION "{unicodedata.unidata_version}"')
    print()
    emit("VITNA_UNI_LETTER", letters)
    emit("VITNA_UNI_NUMBER", numbers)
    print("#endif /* VITNA_UNICODE_DATA_H */")


if __name__ == "__main__":
    main()
