// Writes engine/src/catalog.c from install/catalog.json and the pins it names
// (reference/<pin>/model.json): the models `vitna-anchor plan` may choose, each
// file resolved to the URL it is fetched from at its pin's revision, its size
// and its SHA-256, built into the engine so that the installer needs nothing
// beside it. tests/install.test.mjs fails if catalog.c is not what this writes.
//
//   node engine/tools/gen_catalog.mjs           # write catalog.c
//   node engine/tools/gen_catalog.mjs --check   # exit 1 if catalog.c is not the catalogue's

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { cStringLines } from "./embed_page.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
export const CATALOG = join(ROOT, "install", "catalog.json");
export const SOURCE = join(ROOT, "engine", "src", "catalog.c");

function pin(name) {
  return JSON.parse(readFileSync(join(ROOT, "reference", name, "model.json"), "utf8"));
}

/** The catalogue with every file resolved against its pin. */
export function resolveCatalog(catalog = JSON.parse(readFileSync(CATALOG, "utf8"))) {
  return {
    models: catalog.models.map((m) => ({
      id: m.id,
      title: m.title,
      note: m.note,
      needs: m.needs,
      device: m.device ?? null,
      weights: m.weights ?? null,
      ctx: m.ctx,
      expert_cache: m.expert_cache ?? null,
      files: m.files.map((f) => {
        const p = pin(f.pin);
        const file = p.files.find((x) => x.path === f.path);
        if (!file) throw new Error(`${m.id}: ${f.path} is not pinned in reference/${f.pin}/model.json`);
        return {
          url: `https://huggingface.co/${p.repo}/resolve/${p.revision}/${f.path}`,
          path: `${m.id}/${f.path}`,
          size: file.size,
          sha256: file.sha256,
        };
      }),
    })),
  };
}

export function catalogSource(resolved = resolveCatalog()) {
  return [
    "/**",
    " * catalog.c - The models the installer may install (vitna-anchor plan), each",
    " * file with the URL it is fetched from, its size and its SHA-256: install/",
    " * catalog.json resolved against its pins by engine/tools/gen_catalog.mjs.",
    " * Edit the catalogue or a pin and run that; do not edit this file.",
    " */",
    "",
    "const char vitna_catalog_json[] =",
    cStringLines(JSON.stringify(resolved, null, 1) + "\n") + ";",
    "",
  ].join("\n");
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const want = catalogSource();
  if (process.argv.includes("--check")) {
    let have = "";
    try {
      have = readFileSync(SOURCE, "utf8");
    } catch {}
    if (have !== want) {
      console.error(`${SOURCE} is not install/catalog.json with its pins: run node engine/tools/gen_catalog.mjs`);
      process.exit(1);
    }
    console.log("catalog.c is the catalogue");
  } else {
    writeFileSync(SOURCE, want);
    console.log(`wrote ${SOURCE}`);
  }
}
