/**
 * chat_page.c - The chat page the server answers GET / with: engine/web/chat.html,
 * written here by engine/tools/embed_page.mjs. Edit the page and run that; do
 * not edit this file.
 */

#include <stddef.h>

const char vitna_chat_page[] =
    "<!doctype html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "<meta charset=\"utf-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    "<title>vitna-anchor</title>\n"
    "<style>\n"
    ":root {\n"
    "  --bg: #fbfbf9; --fg: #1d1d1b; --muted: #66665f; --line: #e3e3dd; --soft: #f2f2ee;\n"
    "  --accent: #1d5bb8; --err: #a8261d; --code: #f3f3ef;\n"
    "  color-scheme: light dark;\n"
    "}\n"
    "@media (prefers-color-scheme: dark) {\n"
    "  :root {\n"
    "    --bg: #131312; --fg: #e7e7e2; --muted: #a0a099; --line: #2b2b28; --soft: #1c1c1a;\n"
    "    --accent: #85adff; --err: #ff9a8f; --code: #1c1c1a;\n"
    "  }\n"
    "}\n"
    "* { box-sizing: border-box; }\n"
    "html, body { height: 100%; margin: 0; }\n"
    "body {\n"
    "  background: var(--bg); color: var(--fg); display: flex; flex-direction: column;\n"
    "  font: 15px/1.6 system-ui, -apple-system, \"Segoe UI\", Roboto, sans-serif;\n"
    "}\n"
    "header { display: flex; align-items: baseline; gap: 12px; padding: 12px 16px; border-bottom: 1px solid var(--line); }\n"
    "header .name { font-weight: 600; white-space: nowrap; }\n"
    "header .model { color: var(--muted); font-size: 13px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; min-width: 0; }\n"
    "header .spacer { flex: 1; }\n"
    "button {\n"
    "  font: inherit; font-size: 14px; border: 1px solid var(--line); background: var(--soft); color: var(--fg);\n"
    "  border-radius: 6px; padding: 6px 14px; cursor: pointer; flex-shrink: 0;\n"
    "}\n"
    "button:hover { border-color: var(--muted); }\n"
    "button:disabled { opacity: 0.5; cursor: default; }\n"
    "button:focus-visible, textarea:focus-visible, input:focus-visible, summary:focus-visible, a:focus-visible {\n"
    "  outline: 2px solid var(--accent); outline-offset: 2px;\n"
    "}\n"
    "main { flex: 1; overflow-y: auto; }\n"
    ".log { max-width: 820px; margin: 0 auto; padding: 4px 16px 32px; }\n"
    ".turn { padding: 16px 0; border-bottom: 1px solid var(--line); }\n"
    ".turn:last-child { border-bottom: 0; }\n"
    ".who { font-size: 12px; color: var(--muted); margin-bottom: 4px; }\n"
    ".text { overflow-wrap: anywhere; }\n"
    ".text > :first-child { margin-top: 0; }\n"
    ".text > :last-child { margin-bottom: 0; }\n"
    ".text p, .text ul, .text ol, .text pre, .text table, .text blockquote { margin: 0 0 12px; }\n"
    ".text h1, .text h2, .text h3 { font-size: 16px; margin: 18px 0 8px; }\n"
    ".text ul, .text ol { padding-left: 24px; }\n"
    ".text blockquote { border-left: 2px solid var(--line); padding-left: 12px; color: var(--muted); }\n"
    ".text a { color: var(--accent); }\n"
    ".text table { border-collapse: collapse; display: block; overflow-x: auto; }\n"
    ".text th, .text td { border: 1px solid var(--line); padding: 4px 10px; text-align: left; vertical-align: top; }\n"
    ".text th { background: var(--soft); font-weight: 600; }\n"
    "pre {\n"
    "  background: var(--code); border: 1px solid var(--line); border-radius: 6px; padding: 10px 12px; overflow-x: auto;\n"
    "  font: 13px/1.5 ui-monospace, \"Cascadia Mono\", Consolas, \"SF Mono\", monospace;\n"
    "}\n"
    "code { font: 13px ui-monospace, \"Cascadia Mono\", Consolas, \"SF Mono\", monospace; background: var(--code); padding: 1px 4px; border-radius: 4px; }\n"
    "pre code { background: none; padding: 0; border-radius: 0; }\n"
    ".user .text { white-space: pre-wrap; }\n"
    "details.reasoning { margin: 0 0 10px; }\n"
    "details.reasoning summary { cursor: pointer; font-size: 13px; color: var(--muted); }\n"
    "details.reasoning .thought { white-space: pre-wrap; font-size: 14px; color: var(--muted); border-left: 2px solid var(--line); padding-left: 12px; margin-top: 6px; }\n"
    ".stats { font-size: 12px; color: var(--muted); margin-top: 8px; font-variant-numeric: tabular-nums; }\n"
    ".error { color: var(--err); }\n"
    ".empty { color: var(--muted); padding: 56px 0; text-align: center; }\n"
    "footer { border-top: 1px solid var(--line); padding: 12px 16px 10px; }\n"
    "form { max-width: 820px; margin: 0 auto; display: flex; gap: 8px; align-items: flex-end; }\n"
    "textarea {\n"
    "  flex: 1; min-width: 0; resize: none; min-height: 44px; max-height: 240px; font: inherit; color: var(--fg); background: var(--bg);\n"
    "  border: 1px solid var(--line); border-radius: 6px; padding: 9px 12px;\n"
    "}\n"
    ".options { max-width: 820px; margin: 8px auto 0; display: flex; flex-wrap: wrap; gap: 6px 18px; align-items: center; font-size: 13px; color: var(--muted); }\n"
    ".options label { display: inline-flex; gap: 6px; align-items: center; }\n"
    ".hidden-label { position: absolute; width: 1px; height: 1px; overflow: hidden; clip: rect(0 0 0 0); white-space: nowrap; }\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "<header>\n"
    "  <span class=\"name\">vitna-anchor</span>\n"
    "  <span class=\"model\" id=\"model\">connecting to the server</span>\n"
    "  <span class=\"spacer\"></span>\n"
    "  <button id=\"new\" type=\"button\">New chat</button>\n"
    "</header>\n"
    "<main id=\"scroll\">\n"
    "  <div class=\"log\" id=\"log\"></div>\n"
    "</main>\n"
    "<footer>\n"
    "  <form id=\"form\">\n"
    "    <label for=\"input\" class=\"hidden-label\">Message</label>\n"
    "    <textarea id=\"input\" rows=\"1\" placeholder=\"Message the model\" aria-describedby=\"keys\"></textarea>\n"
    "    <button id=\"send\" type=\"submit\">Send</button>\n"
    "  </form>\n"
    "  <div class=\"options\">\n"
    "    <label id=\"think-option\" hidden><input type=\"checkbox\" id=\"think\" checked> Think before answering</label>\n"
    "    <span id=\"keys\">Enter sends, Shift+Enter starts a new line</span>\n"
    "    <span id=\"status\" role=\"status\"></span>\n"
    "  </div>\n"
    "</footer>\n"
    "<script>\n"
    "\"use strict\";\n"
    "\n"
    "/* ---- The page's pure parts, which tests/chat-page.test.mjs runs in Node ---- */\n"
    "\n"
    "function escapeHtml(s) {\n"
    "  return s.replace(/&/g, \"&amp;\").replace(/</g, \"&lt;\").replace(/>/g, \"&gt;\").replace(/\"/g, \"&quot;\").replace(/'/g, \"&#39;\");\n"
    "}\n"
    "\n"
    "/* Inline Markdown in text already escaped: code spans first, so nothing inside one is formatted. */\n"
    "function renderInline(escaped) {\n"
    "  const parts = escaped.split(/(`[^`]+`)/);\n"
    "  return parts\n"
    "    .map((part, i) => {\n"
    "      if (i % 2 === 1) return \"<code>\" + part.slice(1, -1) + \"</code>\";\n"
    "      return part\n"
    "        .replace(/\\[([^\\]]+)\\]\\((https\?:\\/\\/[^\\s)]+)\\)/g, (m, label, url) => '<a href=\"' + url + '\" target=\"_blank\" rel=\"noopener noreferrer\">' + label + \"</a>\")\n"
    "        .replace(/\\*\\*([^*]+)\\*\\*/g, \"<strong>$1</strong>\")\n"
    "        .replace(/(^|[\\s(])\\*([^*\\s][^*]*\?)\\*(\?=[\\s).,;:!\?]|$)/g, \"$1<em>$2</em>\");\n"
    "    })\n"
    "    .join(\"\");\n"
    "}\n"
    "\n"
    "function isTableRow(line) {\n"
    "  return /^\\s*\\|.*\\|\\s*$/.test(line);\n"
    "}\n"
    "\n"
    "function tableCells(line) {\n"
    "  return line.trim().replace(/^\\|/, \"\").replace(/\\|$/, \"\").split(\"|\").map((c) => c.trim());\n"
    "}\n"
    "\n"
    "/* Markdown to HTML, a safe subset: everything is escaped first, then fenced\n"
    " * code, headings, lists, quotes, tables and paragraphs. A fence still open,\n"
    " * as one is while a reply streams, runs to the end. */\n"
    "function renderMarkdown(text) {\n"
    "  const lines = text.replace(/\\r\\n\?/g, \"\\n\").split(\"\\n\");\n"
    "  const out = [];\n"
    "  let para = [];\n"
    "  const flush = () => {\n"
    "    if (para.length) out.push(\"<p>\" + para.map((l) => renderInline(escapeHtml(l))).join(\"<br>\") + \"</p>\");\n"
    "    para = [];\n"
    "  };\n"
    "  for (let i = 0; i < lines.length; i++) {\n"
    "    const line = lines[i];\n"
    "    const fence = line.match(/^\\s*(```|~~~)\\s*([\\w+#.-]*)\\s*$/);\n"
    "    if (fence) {\n"
    "      flush();\n"
    "      const code = [];\n"
    "      i++;\n"
    "      while (i < lines.length && !lines[i].trim().startsWith(fence[1])) code.push(lines[i++]);\n"
    "      out.push(\"<pre><code\" + (fence[2] \? ' data-lang=\"' + escapeHtml(fence[2]) + '\"' : \"\") + \">\" + escapeHtml(code.join(\"\\n\")) + \"</code></pre>\");\n"
    "      continue;\n"
    "    }\n"
    "    const heading = line.match(/^(#{1,6})\\s+(.*)$/);\n"
    "    if (heading) {\n"
    "      flush();\n"
    "      const level = Math.min(heading[1].length, 3);\n"
    "      out.push(\"<h\" + level + \">\" + renderInline(escapeHtml(heading[2])) + \"</h\" + level + \">\");\n"
    "      continue;\n"
    "    }\n"
    "    if (/^\\s*([-*+]|\\d+[.)])\\s+/.test(line)) {\n"
    "      flush();\n"
    "      const ordered = /^\\s*\\d+[.)]\\s+/.test(line);\n"
    "      const items = [];\n"
    "      while (i < lines.length && /^\\s*([-*+]|\\d+[.)])\\s+/.test(lines[i])) {\n"
    "        items.push(renderInline(escapeHtml(lines[i].replace(/^\\s*([-*+]|\\d+[.)])\\s+/, \"\"))));\n"
    "        i++;\n"
    "      }\n"
    "      i--;\n"
    "      const tag = ordered \? \"ol\" : \"ul\";\n"
    "      out.push(\"<\" + tag + \">\" + items.map((t) => \"<li>\" + t + \"</li>\").join(\"\") + \"</\" + tag + \">\");\n"
    "      continue;\n"
    "    }\n"
    "    if (/^\\s*>/.test(line)) {\n"
    "      flush();\n"
    "      const quote = [];\n"
    "      while (i < lines.length && /^\\s*>/.test(lines[i])) quote.push(lines[i++].replace(/^\\s*>\\s\?/, \"\"));\n"
    "      i--;\n"
    "      out.push(\"<blockquote>\" + quote.map((l) => renderInline(escapeHtml(l))).join(\"<br>\") + \"</blockquote>\");\n"
    "      continue;\n"
    "    }\n"
    "    if (isTableRow(line) && i + 1 < lines.length && /^\\s*\\|\?\\s*:\?-{3,}:\?\\s*(\\|\\s*:\?-{3,}:\?\\s*)*\\|\?\\s*$/.test(lines[i + 1])) {\n"
    "      flush();\n"
    "      const head = tableCells(line);\n"
    "      const rows = [];\n"
    "      i += 2;\n"
    "      while (i < lines.length && isTableRow(lines[i])) rows.push(tableCells(lines[i++]));\n"
    "      i--;\n"
    "      const cell = (tag, c) => \"<\" + tag + \">\" + renderInline(escapeHtml(c)) + \"</\" + tag + \">\";\n"
    "      out.push(\n"
    "        \"<table><thead><tr>\" + head.map((c) => cell(\"th\", c)).join(\"\") + \"</tr></thead><tbody>\" +\n"
    "          rows.map((r) => \"<tr>\" + r.map((c) => cell(\"td\", c)).join(\"\") + \"</tr>\").join(\"\") + \"</tbody></table>\",\n"
    "      );\n"
    "      continue;\n"
    "    }\n"
    "    if (line.trim() === \"\") flush();\n"
    "    else para.push(line);\n"
    "  }\n"
    "  flush();\n"
    "  return out.join(\"\");\n"
    "}\n"
    "\n"
    "/* Server-sent events out of what has arrived: each complete event's data,\n"
    " * and what is left over, which the next read continues. */\n"
    "function parseEvents(buffer) {\n"
    "  const events = [];\n"
    "  let at;\n"
    "  while ((at = buffer.indexOf(\"\\n\\n\")) >= 0) {\n"
    "    const block = buffer.slice(0, at);\n"
    "    buffer = buffer.slice(at + 2);\n"
    "    const data = block.split(\"\\n\").filter((l) => l.startsWith(\"data:\")).map((l) => l.slice(5).replace(/^ /, \"\")).join(\"\\n\");\n"
    "    if (data) events.push(data);\n"
    "  }\n"
    "  return { events, rest: buffer };\n"
    "}\n"
    "\n"
    "/* A chat chunk's effect on the reply so far: its reasoning, its text, how it\n"
    " * ended, its usage, or the error a stream ends with. */\n"
    "function applyChunk(reply, data) {\n"
    "  if (data === \"[DONE]\") {\n"
    "    reply.done = true;\n"
    "    return reply;\n"
    "  }\n"
    "  const chunk = JSON.parse(data);\n"
    "  if (chunk.error) {\n"
    "    reply.error = chunk.error.message || \"The server reported an error.\";\n"
    "    return reply;\n"
    "  }\n"
    "  const choice = chunk.choices && chunk.choices[0];\n"
    "  if (choice && choice.delta) {\n"
    "    if (typeof choice.delta.reasoning_content === \"string\") reply.reasoning += choice.delta.reasoning_content;\n"
    "    if (typeof choice.delta.content === \"string\") reply.content += choice.delta.content;\n"
    "  }\n"
    "  if (choice && choice.finish_reason) reply.finish = choice.finish_reason;\n"
    "  if (chunk.usage) reply.usage = chunk.usage;\n"
    "  return reply;\n"
    "}\n"
    "\n"
    "function newReply() {\n"
    "  return { reasoning: \"\", content: \"\", finish: null, usage: null, error: null, done: false };\n"
    "}\n"
    "\n"
    "/* The line under a reply: its tokens, how fast they came, and the prompt it read. */\n"
    "function statsLine(usage, seconds) {\n"
    "  if (!usage) return \"\";\n"
    "  const n = (x) => x.toLocaleString(\"en-US\");\n"
    "  let s = n(usage.completion_tokens) + \" tokens\";\n"
    "  if (seconds > 0) s += \", \" + (usage.completion_tokens / seconds).toFixed(1) + \" a second\";\n"
    "  s += \", prompt \" + n(usage.prompt_tokens) + \" tokens\";\n"
    "  const cached = usage.prompt_tokens_details && usage.prompt_tokens_details.cached_tokens;\n"
    "  if (cached) s += \" (\" + n(cached) + \" reused)\";\n"
    "  return s;\n"
    "}\n"
    "\n"
    "/* Qwen3's own recommendations, by whether it thinks first; other models' defaults otherwise. */\n"
    "function samplingFor(template, think) {\n"
    "  if (template !== \"qwen3\") return { temperature: 0.7 };\n"
    "  return think \? { temperature: 0.6, top_p: 0.95, top_k: 20 } : { temperature: 0.7, top_p: 0.8, top_k: 20 };\n"
    "}\n"
    "\n"
    "/* ---- The page, in a browser ---- */\n"
    "\n"
    "if (typeof document !== \"undefined\") {\n"
    "  const $ = (id) => document.getElementById(id);\n"
    "  const log = $(\"log\"), scroll = $(\"scroll\"), form = $(\"form\"), input = $(\"input\"), send = $(\"send\");\n"
    "  const status = $(\"status\"), think = $(\"think\");\n"
    "  let server = { model: null, template: \"chatml\", context: 0 };\n"
    "  let history = [];\n"
    "  let running = null;\n"
    "\n"
    "  function atBottom() {\n"
    "    return scroll.scrollHeight - scroll.scrollTop - scroll.clientHeight < 40;\n"
    "  }\n"
    "\n"
    "  function showEmpty() {\n"
    "    log.innerHTML = '<div class=\"empty\">' + (server.model \? \"Ask \" + escapeHtml(server.model) + \" something.\" : \"\") + \"</div>\";\n"
    "  }\n"
    "\n"
    "  function addTurn(role, label) {\n"
    "    const empty = log.querySelector(\".empty\");\n"
    "    if (empty) empty.remove();\n"
    "    const turn = document.createElement(\"section\");\n"
    "    turn.className = \"turn \" + role;\n"
    "    turn.innerHTML = '<div class=\"who\"></div><div class=\"text\"></div>';\n"
    "    turn.querySelector(\".who\").textContent = label;\n"
    "    log.appendChild(turn);\n"
    "    return turn;\n"
    "  }\n"
    "\n"
    "  function drawReply(turn, reply, seconds, live) {\n"
    "    const stick = atBottom();\n"
    "    let html = \"\";\n"
    "    if (reply.reasoning) {\n"
    "      const open = turn.querySelector(\"details.reasoning\");\n"
    "      const label = live && !reply.content \? \"Thinking\" : \"Reasoning\";\n"
    "      html += '<details class=\"reasoning\"' + (open && open.open \? \" open\" : \"\") + \"><summary>\" + label + '</summary><div class=\"thought\">' +\n"
    "        escapeHtml(reply.reasoning.trim()) + \"</div></details>\";\n"
    "    }\n"
    "    html += renderMarkdown(reply.content);\n"
    "    if (reply.error) html += '<p class=\"error\">' + escapeHtml(reply.error) + \"</p>\";\n"
    "    else if (reply.finish === \"length\") html += '<p class=\"error\">The reply stopped at the context\\'s end or the token limit.</p>';\n"
    "    const stats = statsLine(reply.usage, seconds);\n"
    "    if (stats) html += '<div class=\"stats\">' + escapeHtml(stats) + \"</div>\";\n"
    "    turn.querySelector(\".text\").innerHTML = html;\n"
    "    if (stick) scroll.scrollTop = scroll.scrollHeight;\n"
    "  }\n"
    "\n"
    "  function setRunning(on) {\n"
    "    send.textContent = on \? \"Stop\" : \"Send\";\n"
    "    $(\"keys\").hidden = on;\n"
    "    status.textContent = on \? \"Generating. Esc stops it.\" : \"\";\n"
    "  }\n"
    "\n"
    "  async function ask(text) {\n"
    "    history.push({ role: \"user\", content: text });\n"
    "    addTurn(\"user\", \"You\").querySelector(\".text\").textContent = text;\n"
    "    const turn = addTurn(\"assistant\", server.model || \"model\");\n"
    "    const reply = newReply();\n"
    "    const useThink = server.template === \"qwen3\" && think.checked;\n"
    "    const body = {\n"
    "      messages: history.map((m) => ({ role: m.role, content: m.content })),\n"
    "      stream: true,\n"
    "      stream_options: { include_usage: true },\n"
    "      ...samplingFor(server.template, useThink),\n"
    "    };\n"
    "    if (server.model) body.model = server.model;\n"
    "    if (server.template === \"qwen3\") body.chat_template_kwargs = { enable_thinking: useThink };\n"
    "    const controller = new AbortController();\n"
    "    running = controller;\n"
    "    setRunning(true);\n"
    "    let first = 0;\n"
    "    const started = performance.now();\n"
    "    try {\n"
    "      const res = await fetch(\"/v1/chat/completions\", {\n"
    "        method: \"POST\",\n"
    "        headers: { \"content-type\": \"application/json\" },\n"
    "        body: JSON.stringify(body),\n"
    "        signal: controller.signal,\n"
    "      });\n"
    "      if (!res.ok) {\n"
    "        const err = await res.json().catch(() => null);\n"
    "        reply.error = (err && err.error && err.error.message) || \"The server answered \" + res.status + \".\";\n"
    "      } else {\n"
    "        const reader = res.body.getReader();\n"
    "        const decoder = new TextDecoder();\n"
    "        let buffer = \"\";\n"
    "        let drawing = false;\n"
    "        for (;;) {\n"
    "          const { value, done } = await reader.read();\n"
    "          if (done) break;\n"
    "          if (!first) first = performance.now();\n"
    "          const parsed = parseEvents(buffer + decoder.decode(value, { stream: true }));\n"
    "          buffer = parsed.rest;\n"
    "          for (const data of parsed.events) applyChunk(reply, data);\n"
    "          // At most one drawing a frame, however fast the tokens come.\n"
    "          if (!drawing) {\n"
    "            drawing = true;\n"
    "            requestAnimationFrame(() => {\n"
    "              drawing = false;\n"
    "              if (running === controller) drawReply(turn, reply, 0, true);\n"
    "            });\n"
    "          }\n"
    "        }\n"
    "        if (!reply.done && !reply.error) reply.error = \"The stream ended before the reply did.\";\n"
    "      }\n"
    "    } catch (e) {\n"
    "      if (e.name === \"AbortError\") reply.error = \"Stopped.\";\n"
    "      else reply.error = \"Could not reach the server: \" + e.message;\n"
    "    }\n"
    "    const seconds = first \? (performance.now() - first) / 1000 : (performance.now() - started) / 1000;\n"
    "    drawReply(turn, reply, seconds, false);\n"
    "    // What was written stays in the conversation, even a reply that was stopped.\n"
    "    if (reply.content || reply.reasoning) history.push({ role: \"assistant\", content: reply.content });\n"
    "    else history.pop();\n"
    "    running = null;\n"
    "    setRunning(false);\n"
    "    input.focus();\n"
    "  }\n"
    "\n"
    "  function grow() {\n"
    "    input.style.height = \"auto\";\n"
    "    input.style.height = Math.min(input.scrollHeight, 240) + \"px\";\n"
    "  }\n"
    "\n"
    "  form.addEventListener(\"submit\", (e) => {\n"
    "    e.preventDefault();\n"
    "    if (running) {\n"
    "      running.abort();\n"
    "      return;\n"
    "    }\n"
    "    const text = input.value.trim();\n"
    "    if (!text) return;\n"
    "    input.value = \"\";\n"
    "    grow();\n"
    "    ask(text);\n"
    "  });\n"
    "  input.addEventListener(\"keydown\", (e) => {\n"
    "    if (e.key === \"Enter\" && !e.shiftKey && !e.isComposing) {\n"
    "      e.preventDefault();\n"
    "      form.requestSubmit();\n"
    "    }\n"
    "  });\n"
    "  input.addEventListener(\"input\", grow);\n"
    "  document.addEventListener(\"keydown\", (e) => {\n"
    "    if (e.key === \"Escape\" && running) running.abort();\n"
    "  });\n"
    "  $(\"new\").addEventListener(\"click\", () => {\n"
    "    if (running) running.abort();\n"
    "    history = [];\n"
    "    showEmpty();\n"
    "    input.focus();\n"
    "  });\n"
    "\n"
    "  fetch(\"/v1/health\")\n"
    "    .then((r) => r.json())\n"
    "    .then((h) => {\n"
    "      if (!h.model || !h.generation) {\n"
    "        $(\"model\").textContent = h.message || \"This server has no model that generates text.\";\n"
    "        input.disabled = true;\n"
    "        send.disabled = true;\n"
    "        return;\n"
    "      }\n"
    "      server = { model: h.model, template: h.chat_template || \"chatml\", context: h.context || 0 };\n"
    "      $(\"model\").textContent = h.model + (h.context \? \", \" + h.context.toLocaleString(\"en-US\") + \"-token context\" : \"\");\n"
    "      $(\"think-option\").hidden = server.template !== \"qwen3\";\n"
    "      document.title = h.model + \" on vitna-anchor\";\n"
    "      showEmpty();\n"
    "    })\n"
    "    .catch(() => {\n"
    "      $(\"model\").textContent = \"The server did not answer.\";\n"
    "    });\n"
    "  showEmpty();\n"
    "  input.focus();\n"
    "}\n"
    "</script>\n"
    "</body>\n"
    "</html>\n";

const size_t vitna_chat_page_len = sizeof(vitna_chat_page) - 1;
